// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PartTimePt.Datas;

#nullable disable

namespace PartTimePt.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240922174816_ExampleMigration")]
    partial class ExampleMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PartTimePt.Models.DatabaseModel.ExampleTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("NumberA")
                        .HasColumnType("int");

                    b.Property<int>("NumberB")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ExampleTable");
                });
#pragma warning restore 612, 618
        }
    }
}
